TS_annotation_tool/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("overview/corpus/", views.overview_all_corpora, name="overview_all_corpora"),
    path("overview/corpus/<int:corpus_id>", views.overview_per_corpus, name="overview_per_corpus"),
    # path('overview/<str:domain>', views.overview, name='overview'),
    # path('overview/<str:domain>/<int:corpus>', views.overview, name='overview'),
    path("overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>", views.overview_per_doc, name="overview_per_doc"),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/alignment/', include(('alignment.urls', "alignment"), namespace="alignment")),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/', include(('rating.urls', "rating"), namespace="rating")),
    path('evaluation/', include(('evaluation.urls', "evaluation"), namespace="evaluation")),
    path('accounts/', include(('accounts.urls', "accounts"), namespace="accounts")),
    path('data/', include(('data.urls', "data"), namespace="data")),
    path('change_log/', include(('change_log.urls', "change_log"), namespace="change_log")),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/simplification/', include(('simplification.urls', "simplification"), namespace="simplification")),
    path('web_scraping/', include(('web_scraping.urls', "web_scraping"), namespace="web_scraping")),
    re_path('^$', views.home, name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('insert_data', views.insert_data, name="insert_data"),
    path('insert_plain_data', views.insert_data_by_plain_text, name="insert_plain_data"),
    path('insert_web_data', views.insert_data_by_url, name="insert_web_data"),
    path('<int:corpus_id>/doc/<int:doc_pair_id>/sentence/<int:sentence_id>', views.sentence_problem, name="sentence_problem"),
    # path('', views.home, name="home"),
]

data/forms.py
from django import forms
import alignment.models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from multiupload.fields import MultiFileField
from django.core.exceptions import FieldDoesNotExist
import data.models
import TS_annotation_tool.utils
# from crispy_forms.helper import FormHelper

class UploadFileForm(forms.Form):
    file = forms.FileField(validators=[FileExtensionValidator(allowed_extensions=['csv'])],)
    # users = forms.ModelMultipleChoiceField(User.objects.all())
    #, label="Select users to whom the pairs will be assigned"
    #  label="Select a CSV file with manual alignemnts:"


class UploadFilesForm(forms.ModelForm):
    class Meta:
        model = data.models.Corpus
        fields = ["name", "home_page", "author", "license", "license_file", "parallel",  "pre_aligned",
                  "manually_aligned", "pre_split", "to_simplify", "domain", "language", "continuous_text"]

        # help_texts = {
        #     'add_par_nr': data.models.popover_html("Do you want to add paragraph and sentence numbers?"),
        #     'language_level_simple': 'On which language level (following CEFR) ist the simple text? E.g., A1 for easy-to-read language, A2 or B1 for plain language.',
        #     'language_level_complex': 'On which language level (following CEFR) ist the complex text? E.g., C" for everyday language.',
        #     'annotator': 'Which annotator(s) should align, rate or annotate the texts?',
        #     'name': "How should the corpus be called in the annotation tool?",
        #     'home_page': "What is the source of the (web) data)? Please provide at least a author name or homepage.",
        #     'author': 'Who is/are the author(s) of the data? Please provide at least a author name or homepage.',
        #     'license': 'Is the data published under a specific license?',
        #     'license_file': "If a license file is provided, please upload it.",
        #     'domain': 'How can the domain of the data be described?',
        #     'language': "In which language is the data?",
        #     'pre_aligned': "Are the documents already sentence-wise aligned?",
        #     'pre_split': "Are the sentences already split?",
        #     'manually_aligned': "If the texta are already aligned, were they manually or automatically aligned?",
        #     'parallel': "Do comparable or parallel documents exist? If not you can select the to_simplify option.",
        #     'to_simplify': "If no simplified version of a text exists so far you can upload the complex version with this option and simplify the texts yourself.",
        # }
    # corpus_name = forms.CharField(max_length=50)
    # url = forms.URLField()
    # languages = forms.ChoiceField(choices=TS_annotation_tool.utils.LANGUAGE_CHOICES)
    # license = forms.ChoiceField(choices=data.models.list_licenses)
    # domain = forms.CharField(max_length=50)
    find_most_similiar = forms.BooleanField(required=False, help_text=data.models.popover_html('Would you like to calculate similarity between the sentences to get alignment hints?'))
    language_level_simple = forms.ChoiceField(required=False, choices=TS_annotation_tool.utils.language_level_list, help_text=data.models.popover_html('On which language level (following CEFR) ist the simple text? E.g., A1 for easy-to-read language, A2 or B1 for plain language.)'))
    language_level_complex = forms.ChoiceField(choices=TS_annotation_tool.utils.language_level_list, help_text=data.models.popover_html('On which language level (following CEFR) ist the complex text? E.g., C" for everyday language.'))
    professionally_simplified = forms.BooleanField(required=False, help_text=data.models.popover_html("Were the simplified texts professionally simplified?"))
    annotator = forms.ModelMultipleChoiceField(User.objects.all(), help_text=data.models.popover_html('Which annotator(s) should align, rate or annotate the texts?'))
    attachments = MultiFileField(min_num=2)

    def __init__(self, *args, **kwargs):
        super(UploadFilesForm, self).__init__(*args, **kwargs)
        self.fields['annotator'].required = False
        self.fields['license_file'].required = False
        self.fields['home_page'].required = False
        self.fields['author'].required = False
        # self.helper = FormHelper()


class UploadAnnotatedFilesForm(forms.ModelForm):
    class Meta:
        model = data.models.Corpus
        fields = ["name", "home_page", "language", "license", "domain", "parallel"]


class SentenceProblemForm(forms.ModelForm):
    class Meta:
        model = data.models.Sentence
        fields = ["malformed", "malformed_comment"]


class UploadWithCrawlerForm(forms.Form):
    file = forms.FileField()


class UploadRatingForm(forms.Form):
    annotator = forms.ModelChoiceField(User.objects.all())
    file = forms.FileField()

data/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
import data.models, alignment.models
from django.contrib.auth.decorators import user_passes_test

import web_scraping.models
from .forms import UploadFilesForm, UploadAnnotatedFilesForm, SentenceProblemForm, UploadWithCrawlerForm
# from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# @user_passes_test(lambda u: u.is_superuser)
# def home(request):
# 	return render(request, "data/home.html")


@user_passes_test(lambda u: u.is_superuser)
def insert_data(request):
	return render(request, "data/insertion.html")


@user_passes_test(lambda u: u.is_superuser)
def insert_data_by_plain_text(request):
	if request.method == 'POST':
		form_upload = UploadFilesForm(request.POST, request.FILES)
		# if not User.objects.filter(username="automatic"):
		# 	user_machine = User.objects.create_user('automatic', '', 'NoPasswordRequired!')
		# else:
		# 	user_machine = User.objects.get(username="automatic")
		if form_upload.is_valid():
			print(form_upload.cleaned_data)
			files = form_upload.cleaned_data["attachments"]
			# print(files, [dict(file) for file in files], form_upload.cleaned_data["annotator"])
			if data.models.Corpus.objects.filter(name=form_upload.cleaned_data["name"], home_page=form_upload.cleaned_data["home_page"]):
				corpus_tmp = data.models.Corpus.objects.get(name=form_upload.cleaned_data["name"], home_page=form_upload.cleaned_data["home_page"])
				corpus_tmp.add_documents_by_upload(files, form_upload.cleaned_data)
			else:
				corpus_tmp = form_upload.save()
				corpus_tmp.add_documents_by_upload(files, form_upload.cleaned_data)
			return render(request, 'data/success.html', {"number_alignments": 0})
		return render(request, "data/insertion_plain.html", {"form_upload": form_upload})
	else:
		form_upload = UploadFilesForm()
		return render(request, "data/insertion_plain.html", {"form_upload": form_upload,
													   "title": "Data Upload - Text Simplification Annotation Tool"})


@user_passes_test(lambda u: u.is_superuser)
def insert_data_by_url(request):
	if request.method == 'POST':
		form_upload = UploadWithCrawlerForm(request.POST, request.FILES)
		if form_upload.is_valid():
			print(form_upload.cleaned_data)
			file = form_upload.cleaned_data["file"]
			print(file)
			crawler = web_scraping.models.Crawler()
			crawler.crawl_data_to_db(file)
			return render(request, 'data/success.html', {"number_alignments": 0})
		return render(request, "data/insertion_web.html", {"form_upload": form_upload})
	else:
		form_upload = UploadWithCrawlerForm()
		return render(request, "data/insertion_web.html", {"form_upload": form_upload,
													   "title": "Data Upload - Text Simplification Annotation Tool"})


@user_passes_test(lambda u: u.is_superuser)
def insert_annotation(request):
	if request.method == "POST":
		form_upload = UploadFilesForm(request.POST, request.FILES)
	else:
		form_upload = UploadAnnotatedFilesForm()
	return render(request, "data/insertion.html", {"form_upload": form_upload,
												   "title": "Data Upload - Text Simplification Annotation Tool"})


@login_required
def sentence_problem(request, corpus_id, doc_pair_id, sentence_id):
	doc_pair_tmp = get_object_or_404(data.models.DocumentPair, id=doc_pair_id, annotator=request.user, corpus__id=corpus_id)
	sentence_tmp = get_object_or_404(data.models.Sentence, id=sentence_id)
	sentence_content = sentence_tmp.original_content
	if request.method == "POST":
		form = SentenceProblemForm(request.POST, instance=sentence_tmp)
		if form.is_valid():
			sentence_tmp = form.save()
			if sentence_tmp.document.simple_document.all():
				doc_pair_id = sentence_tmp.document.simple_document.values_list("id", flat=True)[0]
			elif sentence_tmp.document.complex_document.all():
				doc_pair_id = sentence_tmp.document.complex_document.values_list("id", flat=True)[0]
			else:
				return render(request, "data/sentence_problem.html",
						  {"form": form, "sentence_content": sentence_content})
			return redirect("alignment:change_alignment", corpus_id=corpus_id, doc_pair_id=doc_pair_id)
	else:
		form = SentenceProblemForm()
	return render(request, "data/sentence_problem.html", {"form": form, "sentence_content": sentence_content})


def check_url_or_404(user=None, corpus_id=None, doc_pair_id=None, sentence_id=None, pair_id=None):
	if corpus_id:
		corpus = get_object_or_404(data.models.Corpus, id=corpus_id)
		if doc_pair_id:
			doc_pair_tmp = get_object_or_404(data.models.DocumentPair, id=doc_pair_id, annotator=user, corpus__id=corpus.id)
			if sentence_id:
				if doc_pair_tmp.simple_document.sentences.filter(id=sentence_id):
					return corpus, doc_pair_tmp, doc_pair_tmp.simple_document.sentences.get(id=sentence_id)
				elif doc_pair_tmp.complex_document.sentences.get(id=sentence_id):
					return corpus, doc_pair_tmp, doc_pair_tmp.complex_document.sentences.get(id=sentence_id)
				else:
					raise Http404('No Sentence matches the given query.')
			elif pair_id:
				if doc_pair_tmp.sentence_alignment_pair.filter(id=pair_id, annotator=user):
					return corpus, doc_pair_tmp, doc_pair_tmp.sentence_alignment_pair.get(id=pair_id, annotator=user)
				else:
					raise Http404('No AlignmentPair matches the given query.')
			else:
				return corpus, doc_pair_tmp, None
		else:
			return corpus, None, None
	else:
		raise Http404('No Corpus matches the given query.')

data/templates/data/home.html
{% extends '../base.html' %}

{% block content %}
    <div class="row subpage_header">
        <div class="col-md-12">
            <h2>Upload Data</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 subpage_content">
            <a href="{%  url 'data:insert_data' %}" title="insert plain data" class="btn btn-default">insert plain data</a>
            <a href="{%  url 'data:insert_aligned_data' %}" title="insert aligned data" class="btn btn-default">insert aligned data</a>

        </div>
    </div>
{% endblock %}

data/templates/data/insertion.html
{% extends '../base.html' %}

{% block content %}
    <div class="row subpage_header">
        <div class="col-md-12">
            <h2>Upload Data Options</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 subpage_content">
            <button><a href="{% url 'data:insert_web_data' %}">Crawl Web Data</a></button>
            <button><a href="{% url 'data:insert_plain_data' %}">Upload Local Data</a></button>
        </div>
    </div>
{% endblock %}

data/templates/data/insertion_aligned.html
{% extends '../base.html' %}

{% block content %}
    <div>The file should be in csv format have the following column order:
        <ul>
            <li>simple sentence</li>
            <li>source of simple sentence</li>
            <li>level of the simple sentence</li>
            <li>access date of simple document</li>
            <li>title of simple document</li>
            <li>license of simple document</li>
            <li>complex sentence</li>
            <li>source of complex sentence</li>
            <li>level of complex sentence</li>
            <li>title of complex document</li>
            <li>access date of complex document</li>
            <li>license of complex document</li>
            <li>domain of the pair</li>
            <li>details regarding the alignment</li>

        </ul>
    </div>
    <form method="post" enctype="multipart/form-data" >{% csrf_token %}
        {{ form.errors }}
        {{ form_upload }}
        <p>
            <button type="submit">Upload and assign</button>
        </p>
    </form>
    {% if data_inserted %}
        Manual alignments successfully uploaded.
    {% endif %}
{% endblock %}

data/templates/data/insertion_plain.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row subpage_header">
        <div class="col-md-12">
            <h2>Upload Data</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 subpage_content">
            <form method="post" enctype="multipart/form-data" >{% csrf_token %}
                {{ form_upload.errors }}
                <p>Please add at least one complex and one simple document. The documents will be aligned based on the identifier in the file name. The file should be organized as follows:</p>
                <ul>
                    <li>
                        first line: # &copy; Origin: source_of_data [last accessed: YYYY-MM-DD]\ttitle_of_document
                    </li>
                    <li>second_line:
                        <ul>
                            <li>If the data is not aligned yet: content of the document. If you want to consider paragraphs, please add "SEPL|||SEPR" between each of the paragraphs.</li>
                            <li>If the data is not aligned but the text is already split into sentences, add one sentence per line. Please specify that the data is already split (pre split). You can also choose this option if you want to realign the data.</li>
                            <li>If the data is already aligned: One line for each aligned text. Each line of the complex and simple file will be aligned. Please specify that the data is already aligned (pre aligned).</li>
                        </ul>
                </ul>
                <p></p>
                <table class="form-check">
                {% for field in form_upload %}
                    <tr>
                        <td>{{ field.help_text|safe }}</td>
                        <td>{{ field.label_tag }}</td>
                        <td>{{ field }}</td>
                    </tr>
                {% endfor %}

                </table>
                <p>
                    <button type="submit">Upload and assign</button>
                </p>
            </form>
            {% if data_inserted %}
                Documents successfully uploaded.
            {% endif %}
        </div>
    </div>
{% endblock %}

data/templates/data/insertion_web.html
{% extends '../base.html' %}

{% block content %}
    <div class="row subpage_header">
        <div class="col-md-12">
            <h2>Upload Data</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 subpage_content">
            <form method="post" enctype="multipart/form-data" >{% csrf_token %}
                {{ form_upload.errors }}
                <p>Please upload a json file containing a "corpora"-object with at least one corpus-description including the following attributes:</p>
                    <ul>
                        <li>url of overview page to crawl,</li>
                        <li>homepage,</li>
                        <li>license,</li>
                        <li>language,</li>
                        <li>language_level_simple,</li>
                        <li>language_level_complex,</li>
                        <li>...</li>
                    </ul>
                <p>
                    For more options have a look at the example file "web_scraping/example_config.json"
                </p>
                {{ form_upload.as_p }}
                <p>
                    <button type="submit">Upload and assign</button>
                </p>
            </form>
            {% if data_inserted %}
                Documents successfully uploaded.
            {% endif %}
        </div>
    </div>
{% endblock %}

data/templates/data/sentence_problem.html
{% extends '../base.html' %}

{% block content %}
    <div class="row subpage_header">
        <div class="col-md-12">
            <h2>Report Sentence Problem</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 subpage_content">
            <h3>Sentence:</h3> {{ sentence_content }}
            <form method="post" enctype="multipart/form-data" >{% csrf_token %}
                {{ form.errors }}
                {{ form.as_p }}
                <p>
                    <button type="submit">Save</button>
                </p>
            </form>
        </div>
    </div>
{% endblock %}

data/templates/data/success.html
{% extends '../base.html' %}

{% block content %}
    <p>
    File successfully uploaded.
    </p>
    {{ number_alignments }} were assigned to users:
        <ul>
            {% for user in selected_users %}
                <li>{{ user }}</li>
            {% endfor %}
        </ul>


{% endblock %}