TS_annotation_tool/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("overview/corpus/", views.overview_all_corpora, name="overview_all_corpora"),
    path("overview/corpus/<int:corpus_id>", views.overview_per_corpus, name="overview_per_corpus"),
    # path('overview/<str:domain>', views.overview, name='overview'),
    # path('overview/<str:domain>/<int:corpus>', views.overview, name='overview'),
    path("overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>", views.overview_per_doc, name="overview_per_doc"),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/alignment/', include(('alignment.urls', "alignment"), namespace="alignment")),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/', include(('rating.urls', "rating"), namespace="rating")),
    path('evaluation/', include(('evaluation.urls', "evaluation"), namespace="evaluation")),
    path('accounts/', include(('accounts.urls', "accounts"), namespace="accounts")),
    path('data/', include(('data.urls', "data"), namespace="data")),
    path('change_log/', include(('change_log.urls', "change_log"), namespace="change_log")),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/simplification/', include(('simplification.urls', "simplification"), namespace="simplification")),
    path('web_scraping/', include(('web_scraping.urls', "web_scraping"), namespace="web_scraping")),
    re_path('^$', views.home, name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

change_log/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('', views.show_changelog, name="change_log"),
    path('', views.show_changelog, name="show_changelog"),
    path('add_item', views.add_item, name="add_item"),
    path('save', views.save_finished, name="save_finished"),
]

data/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('insert_data', views.insert_data, name="insert_data"),
    path('insert_plain_data', views.insert_data_by_plain_text, name="insert_plain_data"),
    path('insert_web_data', views.insert_data_by_url, name="insert_web_data"),
    path('<int:corpus_id>/doc/<int:doc_pair_id>/sentence/<int:sentence_id>', views.sentence_problem, name="sentence_problem"),
    # path('', views.home, name="home"),
]

change_log/models.py
from django.db import models
import TS_annotation_tool.utils


# Create your models here.
class ChangeLog(models.Model):
	finished = models.BooleanField(default=False)
	topic = models.CharField(max_length=250, choices=(("General", "General"),
														("Transformations", "Transformations"),
														("Alignment", "Alignment"),
														("Ratings", "Ratings"),
														("Transformations and Ratings", "Transformations and Raings"),
														("Data", "Data"),
														("Export", "Export"),
														("Simplification", "Simplification")))
	comment = models.TextField(max_length=1000)
	headline = models.TextField(max_length=288)
	created_at = models.DateTimeField(auto_now_add=True)
	finished_at = models.DateTimeField(null=True, blank=True)
	priority = TS_annotation_tool.utils.IntegerRangeField(min_value=1, max_value=5, blank=True, null=True,
														  help_text="Select 1 for highest priority and 5 for lowest priority.")

	def __str__(self):
		return "("+str(self.id)+") "+self.headline

change_log/forms.py
from django import forms
from .models import ChangeLog


class AddChange(forms.ModelForm):
    class Meta:
        model = ChangeLog
        fields = ["headline", "topic", "comment", "priority"]

change_log/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import change_log.forms
import change_log.models
from datetime import datetime


@login_required
def show_changelog(request):
	return render(request, "change_log/change_log.html", {"changes": change_log.models.ChangeLog.objects.all(),
														  "title": "Change Log - Text Simplification Annotation Tool"})


@login_required
def add_item(request):
	if request.POST:
		form = change_log.forms.AddChange(request.POST)
		if form.is_valid():
			form.save()
		return redirect("change_log:show_changelog")
	else:
		form = change_log.forms.AddChange()
		return render(request, "change_log/add_todo.html", {"form": form,
															"title": "Add Todo - Text Simplification Annotation Tool"})


@login_required
def save_finished(request):
	if "todo_item" in request.POST:
		for item in request.POST.getlist("todo_item"):
			if change_log.models.ChangeLog.objects.filter(id=item):
				change_log_item = change_log.models.ChangeLog.objects.get(id=item)
				change_log_item.finished = True
				change_log_item.finished_at = datetime.now()
				change_log_item.save()
	return redirect("change_log:show_changelog")

change_log/templates/change_log/add_todo.html
{% extends '../base.html' %}

{% block content %}
    <h2>Add Item on ToDo List</h2>
    <form method="POST" class="add-form" action={% url 'change_log:add_item' %}>{% csrf_token %}
        <p class="error_form">
            {{ form.errors }}
        </p>
        <div class="row">
            <div class="col-md-12">
                {{ form.as_p }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <button class="btn btn-default" value="save" name="save" type="submit">Save</button>
            </div>
        </div>
    </form>
{% endblock %}

change_log/templates/change_log/change_log.html
{% extends '../base.html' %}

{% block content %}
    <div class="row subclass-header">
        <div class="col-md-12">
            <h2> Change Log</h2>
        </div>
    </div>
    <div class="row error_log">
        <p class="error_form">
            {{ form.errors }}
        </p>
    </div>
    <div class="row subpage content">
        <div class="col-md-12">
            <form method="POST" class="change-form" action={% url 'change_log:save_finished' %}>{% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                        <h3>New Changes:</h3>
                        <ul>
                        {% for change in changes %}
                            {% if change.finished %}
                                <li>
                                    <i class="fas fa-check"></i>
                                    {{ change.headline }} [{{ change.finished_at }}]
                                </li>
                            {% endif %}
                        {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <h3>ToDo List:</h3>
                        <ul>
                        {% for change in changes %}
                            {% if not change.finished %}
                                <li><label for="todo_item"><input type="checkbox" name="todo_item" value="{{ change.id }}"> {{ change.headline }} [{{ change.created_at }}]</label></li>
                            {% endif %}
                        {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <a class="btn btn-default" href="{% url 'change_log:add_item' %}">Add new item</a>
                        <button class="btn btn-default" name="save" value="save" type="submit">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}