TS_annotation_tool/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("overview/corpus/", views.overview_all_corpora, name="overview_all_corpora"),
    path("overview/corpus/<int:corpus_id>", views.overview_per_corpus, name="overview_per_corpus"),
    # path('overview/<str:domain>', views.overview, name='overview'),
    # path('overview/<str:domain>/<int:corpus>', views.overview, name='overview'),
    path("overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>", views.overview_per_doc, name="overview_per_doc"),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/alignment/', include(('alignment.urls', "alignment"), namespace="alignment")),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/', include(('rating.urls', "rating"), namespace="rating")),
    path('evaluation/', include(('evaluation.urls', "evaluation"), namespace="evaluation")),
    path('accounts/', include(('accounts.urls', "accounts"), namespace="accounts")),
    path('data/', include(('data.urls', "data"), namespace="data")),
    path('change_log/', include(('change_log.urls', "change_log"), namespace="change_log")),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/simplification/', include(('simplification.urls', "simplification"), namespace="simplification")),
    path('web_scraping/', include(('web_scraping.urls', "web_scraping"), namespace="web_scraping")),
    re_path('^$', views.home, name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('insert_data', views.insert_data, name="insert_data"),
    path('insert_plain_data', views.insert_data_by_plain_text, name="insert_plain_data"),
    path('insert_web_data', views.insert_data_by_url, name="insert_web_data"),
    path('<int:corpus_id>/doc/<int:doc_pair_id>/sentence/<int:sentence_id>', views.sentence_problem, name="sentence_problem"),
    # path('', views.home, name="home"),
]

evaluation/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('', views.export, name="home"),
    path('export_alignment', views.export_alignment_view, name="export_alignments"),
    path('export_ratings', views.export_ratings_view, name="export_ratings"),
    path('export_transformations', views.export_transformations_view, name="export_transformations"),
    path('export_error_annotation', views.export_error_anno_view, name="export_error_anno"),
    path('export_iaa_alignment', views.export_iaa_alignment, name="export_iaa_alignment"),
    path('export_iaa_transformation', views.export_iaa_transformation, name="export_iaa_transformation"),
    path('export_iaa_rating', views.export_iaa_rating, name="export_iaa_rating"),
    # path('export_full_document', views.full_document_export, name="full_document_export"),
    path('export_full_aligned_document', views.full_aligned_document_export, name="full_aligned_document_export"),
    path('aligned_document_sentences_export', views.aligned_document_sentences_export, name="aligned_document_sentences_export"),
    path('export_text_leveling_data', views.export_text_leveling_data, name="export_text_leveling_data"),
    path('meta_data', views.meta_data, name="meta_data"),
    path('meta_data_export', views.meta_data_export, name="meta_data_export"),
    path('export_transformations_as_iob', views.export_transformations_as_iob, name="export_transformations_as_iob"),

    path('export_data_sheet', views.export_data_sheet, name="export_data_sheet"),
    path('export_user_data', views.export_user_data, name="export_user_data"),
    path('export_meta_data', views.export_meta_data, name="export_meta_data"),
    path('export_all_in_csv_per_use', views.export_all_in_csv_per_use, name="export_all_in_csv_per_use"),
    path('export_alignment_for_crf', views.export_alignment_for_crf, name="export_alignment_for_crf"),

    path("export_references", views.export_corpora_with_references, name="export_references")

    # path('home', views.export, name="home"),
    # path('iaa/', views.iaa, name='iaa'),
]

evaluation/models.py
from django.db import models
from data.models import popover_html

# Create your models here.
class MetaData(models.Model):
	"""
	based on HuggingFace Data Sheets https://github.com/huggingface/datasets/blob/master/templates/README_guide.md
	"""
	summary = models.TextField(help_text=popover_html("Please summarize your data set briefly. "))
	dataset_creation = models.TextField(help_text=popover_html("Please summarize your data set briefly. "))
	language_description = models.TextField(help_text=popover_html(
		"Which texts are included? Why and with which motivate are the texts selected?"))
	domain_decription = models.TextField(help_text=popover_html("Which domains are included?"))
	annotation_process_description = models.TextField(help_text=popover_html("Describe the annotation process."))
	annotator_description = models.TextField(help_text=popover_html("Describe the annotators."))
	sensitive_data_description = models.TextField()
	bias_description = models.TextField()
	social_impact_description = models.TextField()
	limitations_description = models.TextField()
	license_description = models.TextField()
	curator_description = models.TextField()
	citation_description = models.TextField()
	contribution_description = models.TextField()
	task_description = models.TextField()
	homepage = models.CharField(max_length=1)
	repository = models.CharField(max_length=1)
	paper = models.CharField(max_length=1)
	leaderboard = models.CharField(max_length=1)
	point_of_contact = models.CharField(max_length=1)
	data_fields_description = models.TextField()
	language_producers_description = models.TextField()
	collection_description = models.TextField()

evaluation/views.py
import pandas as pd
import json
import csv
import evaluation.models
import rating.models
import data.models
import alignment.models
import accounts.models
from nltk import agreement
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import user_passes_test
# from django.forms.models import model_to_dict
from datetime import datetime
import io
import os
import zipfile
import numpy
import TS_annotation_tool.utils
from django.db.models import Q
from django.contrib.auth.models import User
from sklearn.metrics import cohen_kappa_score
from statsmodels.stats.inter_rater import fleiss_kappa
from .forms import ExportAlignmentForm, MetaDataForm
from django.template.loader import render_to_string
from django.db.models import Count
from django.http import JsonResponse
import jellyfish

def export_rating():  #output_path
	# using same export format as proposed in Alva-Manchego etal. (2020) https://www.aclweb.org/anthology/2020.acl-main.424.pdf
	result_frame = pd.DataFrame(
		columns=["original", "simplification", "original_id", "simplification_id", "aspect", "rater", "rating", "certainty", "comment"])
	i = 0
	non_aspect_fields = ['pair', 'id', 'certainty', 'comment', 'created_at', 'updated_at', 'finished_at', 'duration',
						 'rater']
	aspects = [model_field for model_field in alignment.models.Rating._meta.get_fields() if
			   model_field.name not in non_aspect_fields]
	for pair in alignment.models.Pair.objects.all():
		for pair_rating in pair.rating.all():
			original, original_sentence_id, simplification, simplification_sentence_id, alignment_type = get_texts_and_ids(pair)
			if not simplification or not original:
				continue
			# if jellyfish.levenshtein_distance(original, simplification) <= 1:
			# 	continue
			worker_id = pair_rating.rater.id
			for field in aspects:
				result_frame.loc[i] = [original, simplification, original_sentence_id, simplification_sentence_id, field.name, worker_id, field.value_from_object(pair_rating), pair_rating.certainty, pair_rating.comment]
				i += 1
			i += 1
		i += 1
	return result_frame


def get_automatic_transformations():
	columns = ["original", "simplification", "original_sentence_id", "simplification_sentence_id", "transformation_level", "transformation",
			   "subtransformation", "old text", "new_text", "worker_id"]
	automatic_transformations = list()
	for doc_pair in data.models.DocumentPair.objects.all():
		if doc_pair.simple_document and doc_pair.complex_document:
			simple_sentences = doc_pair.simple_document.sentences.all()  # values_list("original_content", flat=True)
			complex_sentences = doc_pair.complex_document.sentences.all()  # values_list("original_content", flat=True)
			automatic_transformations.extend(get_transformation_no_change(simple_sentences, complex_sentences, doc_pair.id))
			if doc_pair.sentence_alignment_pair.exists():
				print("# todo")  # todo: automatic insertion and deletion
				# automatic_transformations.extend(get_transformation_insertion(simple_sentences))
				# automatic_transformations.extend(get_transformation_deletion(complex_sentences, doc_pair))
	return automatic_transformations


def get_transformation_no_change(simple_sentences, complex_sentences, doc_id):
	list_no_changes = list()
	old_text, new_text = "", ""
	worker_id = "0_auto"  # automated annotated
	transformation_level = "sentence"
	transformation = "no_operation"
	sub_transformation = ""

	simple_sentences_content = [sent.original_content for sent in simple_sentences]
	for complex_sentence in complex_sentences:
		if complex_sentence.original_content in simple_sentences_content:
			original = get_original_sent(complex_sentence, [])[0]
			simplification = get_original_sent(complex_sentence, [])[0]
			list_no_changes.append([original, simplification, complex_sentence.id, "",
								   transformation_level,
								   transformation,
								   sub_transformation,
								   old_text, new_text, worker_id])
	return list_no_changes


# def get_transformation_deletion(complex_sentences, doc_pair):
# 	list_deletions = ()
# 	transformation_level = "paragraph"
# 	transformation = "deletion"
# 	sub_transformation = ""
# 	new_text = ""
# 	worker_id = "_auto"  # automated annotated
# 	# todo pay attention to user
# 	# todo: get all complex sentences ehich have no complex element and add user?
# 	anno = doc_pair.annotator
# 	print(doc_pair)
# 	for annotator_of_doc_pair in doc_pair.annotator.all():
# 		for doc_pair_of_one_annotator in doc_pair.filter(annotator=annotator_of_doc_pair):
# 			print(doc_pair_of_one_annotator)
#
# 	# for complex_sentence in complex_sentences:
# 	# 	for alignment_pair in complex_sentence.complex_element.all():
# 	# 		print("complex", complex_sentence.id, alignment_pair.annotator.all())
# 	return list_deletions
#
#
# def get_transformation_insertion(simple_sentences):
# 	list_insertions = ()
# 	transformation_level = "paragraph"
# 	transformation = "insertion"
# 	sub_transformation = ""
# 	old_text = ""
# 	worker_id = "_auto"  # automated annotated
# 	for simple_sentence in simple_sentences:
# 		if not simple_sentence.simple_element.exists():
# 			print("insert", simple_sentence.id, simple_sentence.simple_element.annotator.all())
# 	return list_insertions

def export_transformation():
	columns = get_row_values(doc_pair=None, alignment_pair=None, rater_id=None, get_columns=True)
	columns = [columns + ["transformation_level", "transformation", "subtransformation", "old text", "new_text", "certainty", "comment"]]
	result_list = list()
	for pair in alignment.models.Pair.objects.filter():
		values = get_row_values(pair.document_pair, pair, "")
		if not values:
			continue
		original, original_sentence_id, simplification, simplification_sentence_id = values[0], values[2], values[1], values[3]
		if not simplification or not original:
			continue
		# if jellyfish.levenshtein_distance(original, simplification) <= 1:
		# 	continue
		for pair_transformations in pair.transformation_of_pair.all():
			if pair_transformations.transformation == "no_operation" and pair_transformations.transformation_level == "sentence":
				continue
			worker_id = pair_transformations.rater.id
			old_text = ' '.join(pair_transformations.complex_token.values_list("text", flat=True))
			new_text = ' '.join(pair_transformations.simple_token.values_list("text", flat=True))
			new_values = values[:-2] + [worker_id, values[-1]] + [pair_transformations.transformation_level, pair_transformations.transformation, pair_transformations.sub_transformation, old_text, new_text, pair_transformations.certainty, pair_transformations.comment]
			result_list.append(new_values)
	result_frame = pd.DataFrame(result_list, columns=columns)
	return result_frame


def export_error_anno():
	columns = get_row_values(doc_pair=None, alignment_pair=None, rater_id=None, get_columns=True)
	columns = [columns + ["error_level", "error_name", "error_subname", "old text", "new_text", "certainty", "comment"]]
	result_list = list()
	for pair in alignment.models.Pair.objects.filter():
		values = get_row_values(pair.document_pair, pair, "")
		if not values:
			continue
		original, original_sentence_id, simplification, simplification_sentence_id = values[0], values[2], values[
			1], values[3]
		if not simplification or not original:
			continue
		# if jellyfish.levenshtein_distance(original, simplification) <= 1:
		# 	continue
		for pair_error_anno in pair.error_of_pair.all():
			# if pair_error_anno.transformation == "no_operation" and pair_error_anno.transformation_level == "sentence":
			# 	continue
			worker_id = pair_error_anno.rater.id
			old_text = ' '.join(pair_error_anno.complex_token.values_list("text", flat=True))
			new_text = ' '.join(pair_error_anno.simple_token.values_list("text", flat=True))
			new_values = values[:-2] + [worker_id, values[-1]] + [pair_error_anno.error_level,
																  pair_error_anno.error,
																  pair_error_anno.sub_error, old_text,
																  new_text, pair_error_anno.certainty,
																  pair_error_anno.comment]
			result_list.append(new_values)
	result_frame = pd.DataFrame(result_list, columns=columns)
	return result_frame


@user_passes_test(lambda u: u.is_superuser)
def export_all_in_csv_per_use(request):
	return export_all(user=True)

@user_passes_test(lambda u: u.is_superuser)
def meta_data_export(request):
	context = {"meta_data": evaluation.models.MetaData.objects.all()[0]}
	# form = MetaDataForm(request.POST, instance=evaluation.models.MetaData.objects.all()[0])
	content = render_to_string('evaluation/meta_data_report.html', context=context)
	response =  HttpResponse(content, content_type="application/html")
	return response

@user_passes_test(lambda u: u.is_superuser)
def meta_data(request):
	# current_meta_data = get_object_or_404(evaluation.models.MetaData, id=0)
	if request.POST:
		if evaluation.models.MetaData.objects.exists():
			form = MetaDataForm(request.POST, instance=evaluation.models.MetaData.objects.all()[0])
		else:
			form = MetaDataForm(request.POST)
		if form.is_valid():
			form.save()
			meta_data_obj = evaluation.models.MetaData.objects.all()[0]
			return render(request, 'evaluation/meta_data_report.html',
						  {"title": "Data Sheet (Meta Data) - Text Simplification Annotation Tool",
						   "meta_data": meta_data_obj})
	else:
		if evaluation.models.MetaData.objects.exists():
			current_meta_data = evaluation.models.MetaData.objects.all()[0]
			form = MetaDataForm(instance=current_meta_data)
		else:
			form = MetaDataForm()
		languages = data.models.Corpus.objects.values_list("language", flat=True).distinct()
		domains = data.models.Corpus.objects.values_list("domain", flat=True).distinct()
		corpora = data.models.Corpus.objects.values_list("name", flat=True).distinct()
		n_corpora = len(data.models.Corpus.objects.all())
		n_doc_pairs = len(data.models.DocumentPair.objects.all())
		n_alignment_pairs = len(alignment.models.Pair.objects.filter(manually_checked=True))

evaluation/templates/evaluation/export_alignment.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row subpage_header">
        <div class="col-md-12">
            <h2>Export Alignment</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 subpage_content">
            <form method="POST">{% csrf_token %}

                <table class="form-check">
                {% for field in form %}
                    <tr>
                        <td>{{ field.help_text|safe }}</td>
                        <td>{{ field.label_tag }}</td>
                        <td>{{ field }}</td>
                    </tr>
                {% endfor %}
                </table>

                <p>
                    <button type="submit">Export Alignment</button>
                </p>


                {#                <input type="checkbox" name="identical" id="identical"><label for="identical"> Add Identical Sentences (automatically aligned)</label>#}
{#                <br>#}
{#                <input type="checkbox" name="addition" id="addition"><label for="addition"> Add Added Sentences (0-1; automatically aligned)</label>#}
{#                <br>#}
{#                <input type="checkbox" name="deletion" id="deletion"><label for="deletion"> Add Deleted Sentences (1-0; automatically aligned)</label>#}
{#                <p>#}
{#                    <button value="export_alignment_per_corpus_and_user" name="export_alignment_per_corpus_and_user">export alignment per corpus and user</button>#}
{#                    <button value="export_alignment_per_user" name="export_alignment_per_user">export alignment per user</button>#}
{#                </p>#}
            </form>
        </div>
    </div>
{% endblock %}

evaluation/templates/evaluation/home.html
{% extends '../base.html' %}

{% block content %}
    <div class="row subpage_header">
        <div class="col-md-12">
            <h2>Evaluation</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 subpage_content">
            <form method="POST">{% csrf_token %}
                <h3>Export Sentence Level</h3>
                <ul >
                    <li class="eval-li">
                        Export ratings per alignment pair, one rating aspect per line.<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_ratings' %}">Export Ratings</a>
                    </li>
                    <li class="eval-li">
                        Export transformations per alignment pair.  Caution: This might take a while.<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_transformations' %}">Export Transformations</a>
                    </li>
                    <li  class="eval-li">
                        Export transformations per alignment pair, label each token with a transformation.  Caution: This might take a while.'<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_transformations_as_iob' %}">Export Transformations in IOB Format</a>
                    </li>
                    <li class="eval-li">
                        Export error annotation per alignment pair.  Caution: This might take a while.<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_error_anno' %}">Export Error Annotation</a>
                    </li>
                    <li  class="eval-li">
                        Export alignment pairs. Specify the download option on the next page.  Caution: This might take a while.<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_alignments' %}">Export Alignment</a>
                    </li>
                    <li  class="eval-li">
                        Combine all annotations (alignments, rating and transformations) and export it in a csv file. Caution: This might take a while.<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_all_in_csv_per_use' %}">export all in csv per user</a>
                    </li>
                    <li  class="eval-li">
                        Export meta data (coming soon).<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_meta_data' %}">Export Meta Data</a>
                    </li>
                    <li  class="eval-li">
                        Export user data (coming soon).<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_user_data' %}">Export User Data</a>
                    </li>
                    <li class="eval-li">
                        Export Corpora with References.<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_references' %}">Export Corpora with References</a>
                    </li>
{#                    <li  class="eval-li">#}
{#                        <i data-toggle="tooltip" data-placement="top" title='' class="fas fa-question-circle">  </i>#}
{#                        <a class="btn btn-default" href="{% url 'evaluation:export_data_sheet' %}">Export Data Sheet</a>#}
{#                    </li>#}
                </ul>
                <h3>Export Document Level</h3>
                <ul>
{#                    <a class="btn btn-default" href="{% url 'evaluation:full_document_export' %}">Export Full Documents</a><br>#}
                    <li  class="eval-li">Export the document pairs of continuous documents sentence-wise. The export contains additions, deletions, no-change pairs and aligned sentence pairs.<br><a class="btn btn-default"  href="{% url 'evaluation:full_aligned_document_export' %}">Export Full Aligned Documents</a></li>
                    <li class="eval-li"><a class="btn btn-default"  href="{% url 'evaluation:aligned_document_sentences_export' %}">Export Sentences of Aligned Documents</a></li>
                    <li class="eval-li"><a class="btn btn-default"  href="{% url 'evaluation:export_text_leveling_data' %}">Export Text Leveling Data of Aligned Documents</a></li>
                </ul>
                <h3>Data Sheet (Meta Data)</h3>
                <ul>
                    <li class="eval-li">Create a data sheet<br>
                        <a class="btn btn-default" href="{% url 'evaluation:meta_data' %}">Add, Edit or Download Data Sheet</a><br>
                    </li>
                </ul>

                {#                <button value="repair_sentence" name="repair_sentence">repair sentence</button>#}
                <h3>Inter Annotator Agreement</h3>
                <ul>
                    <li class="eval-li">
                        Calculate inter annotator agreement for ratings. (coming soon).<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_iaa_rating' %}">Calculate IAA for rating</a><br>
                    </li>
                    <li class="eval-li">
                        Calculate inter annotator agreement for transformations (coming soon).<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_iaa_transformation' %}">Calculate IAA for transformation</a><br>
                    </li>
                    <li class="eval-li">
                        Calculate inter annotator agreement of alignment<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_iaa_alignment' %}">Calculate IAA for alignment</a><br>
                    </li>
                    <li class="eval-li">
                        Export alignments in special format to calculate IAA or to train a automatic aligner.<br>
                        <a class="btn btn-default" href="{% url 'evaluation:export_alignment_for_crf' %}">get alignments for IAA and automatic Alignment</a><br>
                    </li>
                </ul>
            </form>
        </div>
    </div>
{% endblock %}

evaluation/templates/evaluation/iaa_alignment.html
{% extends '../base.html' %}

{% block content %}
    <h1>Inter Annotator Agreement</h1>
    <ul>
        {% for type, type_dict in iaa_dict.items %}
            <li>{{ type }}</li>
            {% for n_annotator, n_annotator_dict in type_dict.items %}
                <ul>
                    <li>{{ n_annotator }}:</li>
                    <ul>
                        {% for doc, value in n_annotator_dict.items %}
                            <li>{{ doc }}: {{ value.name }} {{ value.iaa }} (N= {{ value.n }})</li>
                        {% endfor %}
                    </ul>
                </ul>
                {% endfor %}
        {% endfor %}
        {# <li>Meaning Preservation: {{ iaa_meaning }}</li> #}
        {# <li>Grammaticality: {{ iaa_grammaticality }}</li> #}
        {# <li>Simplicity: {{ iaa_simplicity }}</li> #}
    </ul>
{% endblock %}

evaluation/templates/evaluation/iaa_rating.html
{% extends '../base.html' %}

{% block content %}
    <h1>Inter Annotator Agreement</h1>
    <ul>
        {% for type, type_dict in iaa_dict.items %}
            <li>{{ type }}</li>
            {% for n_annotator, n_annotator_dict in type_dict.items %}
                <ul>
                    <li>{{ n_annotator }}:</li>
                    <ul>
                        {% for doc, value in n_annotator_dict.items %}
                            <li>{{ doc }}: {{ value.name }} {{ value.iaa }} (N= {{ value.n }})</li>
                        {% endfor %}
                    </ul>
                </ul>
                {% endfor %}
        {% endfor %}
        {# <li>Meaning Preservation: {{ iaa_meaning }}</li> #}
        {# <li>Grammaticality: {{ iaa_grammaticality }}</li> #}
        {# <li>Simplicity: {{ iaa_simplicity }}</li> #}
    </ul>
{% endblock %}