TS_annotation_tool/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("overview/corpus/", views.overview_all_corpora, name="overview_all_corpora"),
    path("overview/corpus/<int:corpus_id>", views.overview_per_corpus, name="overview_per_corpus"),
    # path('overview/<str:domain>', views.overview, name='overview'),
    # path('overview/<str:domain>/<int:corpus>', views.overview, name='overview'),
    path("overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>", views.overview_per_doc, name="overview_per_doc"),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/alignment/', include(('alignment.urls', "alignment"), namespace="alignment")),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/', include(('rating.urls', "rating"), namespace="rating")),
    path('evaluation/', include(('evaluation.urls', "evaluation"), namespace="evaluation")),
    path('accounts/', include(('accounts.urls', "accounts"), namespace="accounts")),
    path('data/', include(('data.urls', "data"), namespace="data")),
    path('change_log/', include(('change_log.urls', "change_log"), namespace="change_log")),
    path('overview/corpus/<int:corpus_id>/doc/<int:doc_pair_id>/simplification/', include(('simplification.urls', "simplification"), namespace="simplification")),
    path('web_scraping/', include(('web_scraping.urls', "web_scraping"), namespace="web_scraping")),
    re_path('^$', views.home, name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    re_path('', include('django.contrib.auth.urls')),
    # path("register/", views.register, name="register"),
    path(r'signup/', views.signup, name='register'),
]

alignment/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    # path('', views.home, name="home"),
    #
    # path('change_alignment/<int:alignment_id>', views.change_alignment, name="change_alignment"),
    path('', views.show_alignments, name="change_alignment"),
    path('<int:pair_id>/delete', views.delete_alignment, name="delete_alignment"),
    path('<int:pair_id>/edit', views.edit_alignment, name="edit_alignment"),
    path('add', views.add_alignment, name="add_alignment"),
    path('save', views.save_alignment, name="save_alignment"),
    # path('doc/<int:doc_pair_id>/alignment/<int:pair_id>/save_edit', views.save_edit_alignment, name="save_edit_alignment"),
    path('not_possible', views.alignment_not_possible, name="not_possible"),
    path('<int:sent_id>/edit_by_sent', views.edit_alignment_of_sent, name="edit_alignment_of_sent"),
    # path("overview/", views.PairsListView.as_view()) # overview documents to align

]

change_log/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('', views.show_changelog, name="change_log"),
    path('', views.show_changelog, name="show_changelog"),
    path('add_item', views.add_item, name="add_item"),
    path('save', views.save_finished, name="save_finished"),
]

data/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('insert_data', views.insert_data, name="insert_data"),
    path('insert_plain_data', views.insert_data_by_plain_text, name="insert_plain_data"),
    path('insert_web_data', views.insert_data_by_url, name="insert_web_data"),
    path('<int:corpus_id>/doc/<int:doc_pair_id>/sentence/<int:sentence_id>', views.sentence_problem, name="sentence_problem"),
    # path('', views.home, name="home"),
]

rating/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    # path('', views.home, name='home'),
    # path('home', views.home, name="home"),
    # re_path('^pairs_list', views.pairs_list, name='pairs_list'),
    # path('pairs_list/', views.PairsListView.as_view(), name='pairs_list'),
    # re_path(r'^rate_pair/', views.rate_pair, name='rate_pair'),
    path('transformations/', views.transformations, name='transformations'),
    path('error_operations/', views.error_operations, name='error_operations'),
    path('rating/', views.rating, name='rating'),
    path('rating/<int:pair_id>', views.rate_pair, name='rate_pair'),
    path('transformations/<int:pair_id>', views.select_transformations, name='select_transformation'),
    path('error_operations/<int:pair_id>', views.select_errors, name='select_errors'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>Text Simplification Alignment and Rating</title>
        {% endif %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" />
        <link rel="shortcut icon" type="image/png" style="max-height: 50%;max-width: 100%" href="{% static 'img/favicon.ico' %}"/>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row header">
                <div class="page-header col-md-12">
                    <h1>
                        <a href="{% url 'home' %}" class="headline"><img style="height: 1.1em" src="{%  static 'img/text_simplification_logo_white.png'  %}" alt="text simplification logo"> Text Simplification Annotation Tool </a>
                    </h1>
                </div>
            </div>
            <div class="row main-content">
                <div class="col-md-2 navigation-div">
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Navigation</h4>
                            <ul class="sidebar-nav">
                                {% if user.is_authenticated %}
                                    <li>
                                        <a href="{% url 'overview_all_corpora' %}">
        {#                                <i class="fas fa-book"></i>#}
                                            <img class="fas" style="height: 1.3em;" src="{%  static 'img/book-shelf-icon.png'  %}">
                                            <i class="fa-solid fa-books"></i>
                                            Corpora Overview
                                        </a>
                                    </li>
                                    {% if corpus_id %}
                                        <li>
                                            <a href="{% url 'overview_per_corpus' corpus_id=corpus_id%}">
                                                <i class="fas fa-book"></i> Corpus Overview
                                            </a>
                                        </li>
                                    {% else %}
                                        <li>
                                            <i class="fas fa-book"></i> Corpus Overview
                                        </li>
                                    {% endif %}
                                    {% if doc_pair_id %}
                                        <li>
                                            <a href="{% url 'overview_per_doc' corpus_id=corpus_id doc_pair_id=doc_pair_id %}">
                                                <i class="fas fa-file-alt"></i>
                                                Document Overview
                                            </a>
                                            <ul class="sidebar-nav">
                                                {% if pair_id %}
                                                    <li>
                                                    {% if 'simplification' in request.path %}
                                                        <a href="{% url 'simplification:edit' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair_id %}">
                                                    {% else %}
                                                        <a href="{% url 'alignment:edit_alignment' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair_id %}">
                                                    {% endif %}
                                                            <i class="fa-solid fa-arrow-right-arrow-left"></i>
                                                            Alignment
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="{% url 'rating:select_transformation' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair_id %}">
                                                            <i class="fas fa-route"></i>
                                                            Transformation Annotation
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="{% url 'rating:rate_pair' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair_id %}">
                                                            <i class="fas fa-balance-scale-left"></i>
                                                            Rating
                                                        </a>
                                                    </li>
                                                {% else %}
                                                    <li>
                                                    {% if 'simplification' in request.path %}
                                                        <a href="{% url 'simplification:simplify' corpus_id=corpus_id doc_pair_id=doc_pair_id %}">
                                                    {% else %}
                                                        <a href="{% url 'alignment:change_alignment' corpus_id=corpus_id doc_pair_id=doc_pair_id %}">
                                                    {% endif %}
                                                            <i class="fa-solid fa-arrow-right-arrow-left"></i>
                                                            Alignment
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="{% url 'rating:transformations' corpus_id=corpus_id doc_pair_id=doc_pair_id %}">
                                                            <i class="fas fa-route"></i>
                                                            Transformation Annotation
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="{% url 'rating:rating' corpus_id=corpus_id doc_pair_id=doc_pair_id %}">
                                                            <i class="fas fa-balance-scale-left"></i>
                                                            Rating
                                                        </a>
                                                    </li>
                                                {% endif %}
                                            </ul>
                                        </li>
                                        {% else %}
                                        <li>
                                            <i class="fas fa-file-alt"></i>
                                            Document Overview
                                            <ul class="sidebar-nav">
                                                <li><i class="fa-solid fa-arrow-right-arrow-left"></i> Alignment</li>
                                                <li><i class="fas fa-route"></i> Transformation Annotation</li>
                                                <li><i class="fas fa-balance-scale-left"></i> Rating</li>
                                            </ul>
                                        </li>
                                    {% endif %}
                                    <li>

                                        <a href="{% url 'change_log:change_log' %}">
                                            <i class="fas fa-cogs"></i>
                                            Change Log
                                        </a>
                                    </li>
                                    {% if user.is_superuser %}
                                        <li>
                                            <a href="{% url 'data:insert_data' %}">
                                                <i class="fas fa-upload"></i>
                                                Data Upload
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'evaluation:home' %}">
                                                <i class="fas fa-download"></i>
                                                Evaluation
                                            </a>
                                        </li>
                                    {% endif %}
        {#                            <li><a href="{% url 'overview' %}">Rating</a></li>#}
        {#                            <li><a href="{% url 'simplification:home' %}">Simplification</a></li>#}
        {#                            <li>User: {{ user.get_username }}</li>#}
                                    <li>
                                        <a href="{% url 'accounts:logout'%}?next={{request.path}}">
                                            <i class="fas fa-sign-out-alt"></i>
                                            Logout ({{ user.get_username }})
                                        </a>
                                    </li>
                                {% else %}
                                    <li>
                                        <a href="{% url 'accounts:login'%}?next={{request.path}}">
                                            <i class="fas fa-sign-out-alt"></i>
                                            Login
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'accounts:register'%}?next={{request.path}}">
                                            <i class="fas fa-user-plus"></i>
                                            Sign up
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                {% if notes == "alignment" %}
                    {% include './alignment/alignment_notes.html' %}
                {% endif %}
                </div>
                <div class="col-md-10 content-div">
                    {% include 'messages.html' %}
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <hr>
            <div class="row footer">
                <div class="col-md-12" style="text-align: center">
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            &copy; 2022 Regina Stodden and Laura Kallmeyer | <a href="https://www.hhu.de/datenschutzerklaerung" title="Link to Privacy Statement" target="_blank">Privacy Statement</a>
                        </div>
                        <div class="col-md-3"></div>
                    </div>

                </div>
            </div>
        </div>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-10" style="text-align: center">
            <div class="row">
                <p>Welcome to the text simplification annotation tool. </p>
                <p>You can find instructions on how to use the annotation guidelines including the annotation schema  <a href="https://github.com/rstodden/TS_annotation_tool/tree/master/annotation_schema" title="Link to annotation guidelines and schema">here</a>.</p>
            </div>
            <div class="row">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/n6oJofcNjw8" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="row">
                <p>If you have any questions feel free to contact <a href="mailto:regina.stodden@hhu.de">Regina Stodden</a> </p>
            </div>


        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <a href="https://github.com/rstodden/TS_annotation_tool">TS-anno</a> is a platform for text simplification corpora building provided by <a href="https://user.phil.hhu.de/~stodden/" title="Link to the website of Regina Stodden">Regina Stodden</a> and <a href="https://user.phil.hhu.de/kallmeyer/" title="Link to the website of Laura Kallmeyer">Laura Kallmeyer</a>. Only the respective operator of the annotation tool is responsible for the content.
        </div>
        <div class="col-md-5"></div>
    </div>

{% endblock %}

templates/messages.html
{% for message in messages %}
  <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
        {{ message }}
        {{ form.errors }}
      </div>
  </div>
{% endfor %}

templates/overview.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-12">
            <h1>
                <i class="fas fa-book"></i>
                Corpora Overview
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="corpus">
                <thead>
                    <tr>
                        <th class="corpus">ID</th>
                        <th class="corpus">Corpus</th>
                        <th class="corpus">Title</th>
                        <th class="corpus">Domain</th>
                        <th class="corpus">Simple Level</th>
                        <th class="corpus">Complex Level</th>
                        <th class="corpus">Last Change</th>
                        <th class="corpus">Aligned</th>
                        <th class="corpus">Rating</th>
                        <th class="corpus">Transformation</th>
                    </tr>
                </thead>
                <tbody>
                    {% for corpus_name, corpus in corpora.items %}
                        {% for doc_pair_id, doc_pair in corpus.items %}
                            <tr>
                                <td class="corpus">{{ doc_pair_id }}</td>
                                <td class="corpus">{{ corpus_name }}</td>
                                <td class="corpus">
                                    <a href="{% url 'overview_per_doc' doc_pair_id=doc_pair_id %}">{{ doc_pair.title }}</a>
                                </td>
                                <td class="corpus">{{ doc_pair.domain }}</td>
                                <td class="corpus">{{ doc_pair.simple_level }}</td>
                                <td class="corpus">{{ doc_pair.complex_level }}</td>
                                <td class="corpus">{{ doc_pair.last_change }}</td>
                                {% if doc_pair.no_alignment_possible %}
                                    <td class="corpus" style="text-align: center"><i class="fas fa-ban"></i></td>
                                {% elif doc_pair.aligned %}
                                    <td class="corpus" style="text-align: center"><i class="fas fa-check-circle" style="color: #8ACBAE"></i></td>
                                {% else %}
                                    <td class="corpus" style="text-align: center"><i class="fas fa-times-circle" style="color: indianred;"></i></td>
                                {% endif %}
                                <td class="corpus">{{ doc_pair.rating }} %</td>
                                <td class="corpus">{{ doc_pair.transformations }} %</td>
                            </tr>
                        {% endfor %}

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/overview_per_doc.html
{% extends 'base.html' %}

{% block content %}
    <div class="row subpage-header">
        <div class="col-md-12">
            <h1>
                <i class="fas fa-file-alt"></i>
                Document Overview: {{ doc_title }}
            </h1>
        </div>
    </div>
    <div class="row subpage-content">
        <div class="col-md-12">
{#            <h2>Document: {{ doc_title }}</h2>#}
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-default" href="{% url 'alignment:change_alignment' corpus_id=corpus_id doc_pair_id=doc_pair_id %}"><i class="fa-solid fa-arrow-right-arrow-left"></i> Continue Alignment</a><br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <form method="POST" class="alignment-form" action={% url 'alignment:change_alignment' corpus_id=corpus_id doc_pair_id=doc_pair_id %}>{% csrf_token %}
                        <table class="doc">
                            <thead>
                            <tr>
                                <td class="doc">complex sentence</td>
                                <td class="doc">simple sentence</td>
                                <td class="doc">Rating</td>
                                <td class="doc">Transformation</td>
                                <td class="doc">Error Annotation</td>
                                <td class="doc">Alignment</td>

                            </tr>
                            </thead>
                            <tbody>
                            {% for pair in alignments %}
                                <tr>
                                    <td class="doc">
                                        {% for sentence in pair.complex_elements.all %}
                                            {{ sentence.original_content|slice:50 }}
                                            {% if sentence.original_content|length > 50 %}
                                                ...
                                            {% endif %}
                                        {% endfor %}
                                    </td>

                                    <td class="doc">
                                        {% for sentence in pair.simple_elements.all %}
                                            {{ sentence.original_content|slice:50 }}
                                            {% if sentence.original_content|length > 50 %}
                                                [...]
                                            {% endif %}
                                        {% endfor %}
                                    </td>

                                    <td class="doc">
                                        {% if pair.rating.all %}
                                            <a href="{% url 'rating:rate_pair' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair.id %}" class="btn btn-default">
                                                <i class="fas fa-edit"></i> edit
                                            </a>
                                        {% else %}
                                            <a href="{% url 'rating:rate_pair' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair.id %}" class="btn btn-default">
                                                <i class="fas fa-plus-circle"></i> add
                                            </a>
                                        {% endif %}
                                    </td>
                                    <td class="doc">
                                        {% if pair.transformation_of_pair.all %}
                                            <a href="{% url 'rating:select_transformation' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair.id %}" class="btn btn-default">
                                                <i class="fas fa-edit"></i> edit
                                            </a>
                                        {% else %}
                                            <a href="{% url 'rating:select_transformation' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair.id %}" class="btn btn-default">
                                                <i class="fas fa-plus-circle"></i> add
                                            </a>
                                        {% endif %}
                                    </td>
                                    <td class="doc">
                                        {% if pair.error_of_pair.all %}
                                            <a href="{% url 'rating:select_errors' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair.id %}" class="btn btn-default">
                                                <i class="fas fa-edit"></i> edit
                                            </a>
                                        {% else %}
                                            <a href="{% url 'rating:select_errors' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair.id %}" class="btn btn-default">
                                                <i class="fas fa-plus-circle"></i> add
                                            </a>
                                        {% endif %}
                                    </td>
                                    <td class="doc">
                                        <a class="btn btn-default" title="edit alignment of pair" href="{% url 'alignment:edit_alignment' corpus_id=corpus_id doc_pair_id=doc_pair_id pair_id=pair.id %}"><i class="fas fa-edit"></i> edit </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                {% if alignments.has_other_pages %}
                    <ul class="pagination">
                        {% if alignments.has_previous and alignments.previous_page_number != 0 %}
                            <li><a class="btn btn-default" href="?page=1" title="first page"><i class="fas fa-fast-backward"></i> First Pairs</a></li>
                        {% else %}
                            <li class="disabled"><span><i class="fas fa-fast-backward"></i></span></li>
                        {% endif %}
                        {% if alignments.has_previous %}
                            <li><a class="btn btn-default" href="?page={{ alignments.previous_page_number }}" title="previous page">
                                <i class="fas fa-backward"></i> Previous Pairs
                            </a></li>
                        {% else %}
                            <li class="disabled"><span><i class="fas fa-backward"></i></span></li>
                        {% endif %}
                        {% for i in alignments.paginator.page_range %}
                            <!--{% if forloop.counter < i|add:3 and forloop.counter < i|add:"-3" %}-->
                                {% if alignments.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li><a href="?page={{ i }}" title="page {{ i }}">{{ i }}</a></li>
                                {% endif %}
                                <!--{% endif %}-->
                        {% endfor %}
                        {% if alignments.has_next %}
                            <li><a class="btn btn-default" href="?page={{ alignments.next_page_number }}" title="next page">
                                Next Pairs <i class="fas fa-forward"></i>
                            </a></li>
                        {% else %}
                            <li class="disabled"><span><i class="fas fa-forward"></i></span></li>
                        {% endif %}
                        {% if alignments.has_next and alignments.paginator.num_pages != alignments.next_page_number %}
                            <li><a class="btn btn-default" href="?page={{ alignments.paginator.num_pages }}" title="last page">
                                 Last Pairs <i class="fas fa-fast-forward"></i>
                            </a></li>
                            {% else %}
                            <li class="disabled"><span><i class="fas fa-fast-forward"></i></span></li>
                        {% endif %}
                    </ul>
                {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    {% if prev_doc_pair_id %}
                        <a class="btn btn-default" href="{% url 'overview_per_doc' corpus_id=corpus_id doc_pair_id=prev_doc_pair_id %}"><i class="fas fa-arrow-circle-left"></i> Previous Document</a>
                    {% else %}
                        <a class="btn btn-default" disabled><i class="fas fa-arrow-circle-left"></i> Previous Document</a>
                    {% endif %}
                    {% if next_doc_pair_id %}
                        <a class="btn btn-default" href="{% url 'overview_per_doc' corpus_id=corpus_id doc_pair_id=next_doc_pair_id %}"><i class="fas fa-arrow-circle-right"></i> Next Document</a>
                    {% else %}
                        <a class="btn btn-default" disabled><i class="fas fa-arrow-circle-right"></i> Next Document</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/todo.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            This page is currently under development.
        </div>
    </div>

{% endblock %}